### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [SukkaW/posthtml-external-link#2]
@SukkaW  Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by SukkaW** [comment]
> I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

@Scrum 

It will be an honor to move the plugin to the PostHTML organization. I have sent an invitation to you.

**Comment by Scrum** [comment]
@SukkaW I have to be right `owner` to be able to move

**Comment by SukkaW** [comment]
@Scrum 

![image](https://user-images.githubusercontent.com/40715044/99962331-f9a64800-2dca-11eb-8302-fb32b27dcffa.png)

It appears that I could only add you as a `collaborator`, per [GitHub Docs](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-for-a-repository-owned-by-a-user-account).

Maybe only I have permission to move the repo.

**Comment by Scrum** [comment]
You can move the repository to my account, move it to `posthtml` subject to your rights to this repository

**Comment by SukkaW** [comment]
@Scrum Since I have no permission to create new repo under posthtml, I will transfer the repo to you first. The transfer request has been sent.

**Comment by Scrum** [comment]
@SukkaW Done, check your rights

**Comment by SukkaW** [comment]
> Done, check your rights

@Scrum Yeah, I still have access to the repo's settings page. I will open PRs to add the plugin to posthtml plugin lists later. And I believe it is ok to close this issue for now.
